name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    if: ${{ contains(github.event.pull_request.title, ':review') }}
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.REVIEW_API_KEY }}
          LANGUAGE: Japanese
          OPENAI_API_ENDPOINT: ${{ secrets.REVIEW_API_ENDPOINT }}
          MODEL: ${{ secrets.REVIEW_API_MODEL }}
          PROMPT: |
            あなたは経験豊富なRust開発者です。
            以下のRustコードをレビューし、重大な問題点のみを簡潔なマークダウンで報告してください。

            レビュー観点：
            - バグ: 実行時エラー、クラッシュ、未定義動作を引き起こす可能性のあるもの
            - セキュリティ: 重大な脆弱性
            - パフォーマンス: 著しいボトルネック
            - 設計: 保守性を著しく損なう構造
            - 可読性：可読性が極めて低い箇所
            - テスト: テストが不足し、クリティカルな問題につながる場合

            軽微な問題、好みの問題は無視してください。
            問題がない場合は「特筆すべき問題はありません。」と報告してください。

            報告形式：
            ```markdown
            ### レビュータイトル (例: バグ修正)

            *   **観点:** (例: バグとエラー)
            *   **問題の簡潔な説明:**
            *   **改善提案:**
            *   **コード例 (必要な場合):** 差分がわかりやすいように記述
            ```
          top_p: 1
          temperature: 1
          max_tokens: 4096
          MAX_PATCH_LENGTH: 4096
          IGNORE_PATTERNS: *.md
          INCLUDE_PATTERNS: *.rs
